# -*- coding: utf-8 -*
cins, cdel = 3.0, 3.0
horiz_adj = 1.5
similar_letter = 2.0
vert_adj = 2.5
diag_adj = 3.5
no_adj = 5.5

KeyboardGraph = {'а': {'к':vert_adj,
                       'е': diag_adj,
                       'п': horiz_adj,
                       'в': horiz_adj,
                       'м': vert_adj,
                       'с': vert_adj,
                       'у': diag_adj,
                       'я': similar_letter,
                       'и': similar_letter,
                       'о': similar_letter,
                       'б': no_adj,
                       'г': no_adj,
                       'д': no_adj,
                       'ж': no_adj,
                       'з': no_adj,
                       'и': no_adj,
                       'й': no_adj,
                       'к': no_adj,
                       'л': no_adj,
                       'н': no_adj,
                       'р': no_adj,
                       'т': no_adj,
                       'ф': no_adj,
                       'х': no_adj,
                       'ц': no_adj,
                       'ч': no_adj,
                       'ш': no_adj,
                       'щ': no_adj,
                       'ъ': no_adj,
                       'ы': no_adj,
                       'ь': no_adj,
                       'э': no_adj,
                       'ю': no_adj},
                 'б': {'л': vert_adj,
                       'д': vert_adj,
                       'ю': horiz_adj,
                       'ь': horiz_adj,
                       'п': similar_letter,
                       # ------
                       'в': no_adj,
                       'г': no_adj,
                       'е': no_adj,
                       'ж': no_adj,
                       'з': no_adj,
                       'и': no_adj,
                       'й': no_adj,
                       'к': no_adj,
                       'л': no_adj,
                       'м': no_adj,
                       'н': no_adj,
                       'о': no_adj,
                       'р': no_adj,
                       'с': no_adj,
                       'т': no_adj,
                       'у': no_adj,
                       'ф': no_adj,
                       'х': no_adj,
                       'ц': no_adj,
                       'ч': no_adj,
                       'ш': no_adj,
                       'щ': no_adj,
                       'ъ': no_adj,
                       'ы': no_adj,
                       'э': no_adj,
                       'я': no_adj},
                 'в': {'у': vert_adj,
                       'ч': vert_adj,
                       'с': vert_adj,
                       'ы': horiz_adj,
                       'ц': diag_adj,
                       'к': diag_adj,
                       'ф': similar_letter,
                       'г': similar_letter,
                       # ------
                       'д': no_adj,
                       'е': no_adj,
                       'ж': no_adj,
                       'з': no_adj,
                       'и': no_adj,
                       'й': no_adj,
                       'л': no_adj,
                       'м': no_adj,
                       'н': no_adj,
                       'о': no_adj,
                       'п': no_adj,
                       'р': no_adj,
                       'т': no_adj,
                       'х': no_adj,
                       'ш': no_adj,
                       'щ': no_adj,
                       'ъ': no_adj,
                       'ь': no_adj,
                       'э': no_adj,
                       'ю': no_adj,
                       'я': no_adj},
                  'г': {'о': vert_adj,
                       'н': horiz_adj,
                       'ш': horiz_adj,
                       'р': diag_adj,
                       'л': diag_adj,
                       'к': similar_letter,
                       'х': similar_letter,
                       # ------
                       'д': no_adj,
                       'е': no_adj,
                       'ж': no_adj,
                       'з': no_adj,
                       'и': no_adj,
                       'й': no_adj,
                       'м': no_adj,
                       'п': no_adj,
                       'с': no_adj,
                       'т': no_adj,
                       'у': no_adj,
                       'ф': no_adj,
                       'ц': no_adj,
                       'ч': no_adj,
                       'щ': no_adj,
                       'ъ': no_adj,
                       'ы': no_adj,
                       'ь': no_adj,
                       'э': no_adj,
                       'ю': no_adj,
                       'я': no_adj},
                  'д': {'щ': vert_adj,
                       'ж': horiz_adj,
                       'л': horiz_adj,
                       'з': diag_adj,
                       'ш': diag_adj,
                       'ю': vert_adj,
                       'т': similar_letter,
                       # ------
                       'е': no_adj,
                       'и': no_adj,
                       'й': no_adj,
                       'к': no_adj,
                       'м': no_adj,
                       'н': no_adj,
                       'о': no_adj,
                       'п': no_adj,
                       'р': no_adj,
                       'с': no_adj,
                       'у': no_adj,
                       'ф': no_adj,
                       'х': no_adj,
                       'ц': no_adj,
                       'ч': no_adj,
                       'ъ': no_adj,
                       'ы': no_adj,
                       'ь': no_adj,
                       'э': no_adj,
                       'я': no_adj},
                 'е': {'п': vert_adj,
                       'к': horiz_adj,
                       'н': horiz_adj,
                       'р': diag_adj,
                       'и': similar_letter,
                       'э': similar_letter,
                       
                        # ------
                       'ж': no_adj,
                       'з': no_adj,
                       'й': no_adj,
                       'к': no_adj,
                       'л': no_adj,
                       'м': no_adj,
                       'о': no_adj,
                       'с': no_adj,
                       'т': no_adj,
                       'у': no_adj,
                       'ф': no_adj,
                       'х': no_adj,
                       'ц': no_adj,
                       'ч': no_adj,
                       'ш': no_adj,
                       'щ': no_adj,
                       'ъ': no_adj,
                       'ы': no_adj,
                       'ь': no_adj,
                       'ю': no_adj,
                       'я': no_adj},
                 'ж': {'з': vert_adj,
                       'э': horiz_adj,
                       'х': diag_adj,
                       'щ': diag_adj,
                       'ю': vert_adj,
                       'ш': similar_letter,
                      
                        # ------
                       'и': no_adj,
                       'й': no_adj,
                       'к': no_adj,
                       'л': no_adj,
                       'м': no_adj,
                       'н': no_adj,
                       'о': no_adj,
                       'п': no_adj,
                       'р': no_adj,
                       'с': no_adj,
                       'т': no_adj,
                       'у': no_adj,
                       'ф': no_adj,
                       'ц': no_adj,
                       'ч': no_adj,
                       'ъ': no_adj,
                       'ы': no_adj,
                       'ь': no_adj,
                       'я': no_adj},
                  'з': {'х': horiz_adj,
                       'щ': horiz_adj,
                       'э': diag_adj,
                       'с': similar_letter,

                        # ------
                       'и': no_adj,
                       'й': no_adj,
                       'к': no_adj,
                       'л': no_adj,
                       'м': no_adj,
                       'н': no_adj,
                       'о': no_adj,
                       'п': no_adj,
                       'р': no_adj,
                       'т': no_adj,
                       'у': no_adj,
                       'ф': no_adj,
                       'ц': no_adj,
                       'ч': no_adj,
                       'ш': no_adj,
                       'ъ': no_adj,
                       'ы': no_adj,
                       'ь': no_adj,
                       'ю': no_adj,
                       'я': no_adj},
                 'и': {'м': horiz_adj,
                       'т': horiz_adj,
                       'п': diag_adj,
                       'р': diag_adj,

                       # -------
                       'й': no_adj,
                       'к': no_adj,
                       'л': no_adj,
                       'н': no_adj,
                       'о': no_adj,
                       'с': no_adj,
                       'у': no_adj,
                       'ф': no_adj,
                       'х': no_adj,
                       'ц': no_adj,
                       'ч': no_adj,
                       'ш': no_adj,
                       'щ': no_adj,
                       'ъ': no_adj,
                       'ы': no_adj,
                       'ь': no_adj,
                       'э': no_adj,
                       'ю': no_adj,
                       'я': no_adj},
                 
                  'й': {'ф': vert_adj,
                       'ц': horiz_adj,
                       'ы': diag_adj,
                       'и': similar_letter,
                        
                       # ------
                       'к': no_adj,
                       'л': no_adj,
                       'м': no_adj,
                       'н': no_adj,
                       'о': no_adj,
                       'п': no_adj,
                       'р': no_adj,
                       'с': no_adj,
                       'т': no_adj,
                       'у': no_adj,
                       'х': no_adj,
                       'ч': no_adj,
                       'ш': no_adj,
                       'щ': no_adj,
                       'ъ': no_adj,
                       'ь': no_adj,
                       'э': no_adj,
                       'ю': no_adj,
                       'я': no_adj},
                 
                  'к': {'у': horiz_adj,
                       'п': diag_adj,
                       'г': similar_letter,
                        
                       # ------
                       'л': no_adj,
                       'м': no_adj,
                       'н': no_adj,
                       'о': no_adj,
                       'р': no_adj,
                       'с': no_adj,
                       'т': no_adj,
                       'ф': no_adj,
                       'х': no_adj,
                       'ц': no_adj,
                       'ч': no_adj,
                       'ш': no_adj,
                       'щ': no_adj,
                       'ъ': no_adj,
                       'ы': no_adj,
                       'ь': no_adj,
                       'э': no_adj,
                       'ю': no_adj,
                       'я': no_adj},
                 'л': {'о': horiz_adj,
                       'ш': vert_adj,
                       'ю': diag_adj,
                       'щ': diag_adj,
                       'ь': diag_adj,
                       'р': similar_letter,
                       'м': similar_letter,
                       'н': no_adj,
                       'п': no_adj,
                       'с': no_adj,
                       'т': no_adj,
                       'у': no_adj,
                       'ф': no_adj,
                       'х': no_adj,
                       'ц': no_adj,
                       'ч': no_adj,
                       'ъ': no_adj,
                       'ы': no_adj,
                       'э': no_adj,
                       'я': no_adj},
                 'м': {'с': horiz_adj,
                       'р': diag_adj,
                       'п': diag_adj,
                       'н': similar_letter,
                       'о': no_adj,
                       'с': no_adj,
                       'т': no_adj,
                       'у': no_adj,
                       'ф': no_adj,
                       'х': no_adj,
                       'ц': no_adj,
                       'ч': no_adj,
                       'ш': no_adj,
                       'щ': no_adj,
                       'ъ': no_adj,
                       'ы': no_adj,
                       'ь': no_adj,
                       'э': no_adj,
                       'ю': no_adj,
                       'я': no_adj},
                 'н': {'р': vert_adj,
                       'п': diag_adj,
                       'о': diag_adj,
                       'с': no_adj,
                       'т': no_adj,
                       'у': no_adj,
                       'ф': no_adj,
                       'х': no_adj,
                       'ц': no_adj,
                       'ч': no_adj,
                       'ш': no_adj,
                       'щ': no_adj,
                       'ъ': no_adj,
                       'ы': no_adj,
                       'ь': no_adj,
                       'э': no_adj,
                       'ю': no_adj,
                       'я': no_adj},
                 'о': {'р': horiz_adj,
                       'т': vert_adj,
                       'ш': vert_adj,
                       'щ': diag_adj,
                       'ь': vert_adj,
                       'у': similar_letter,
                       'ы': similar_letter,
                       'п': no_adj,
                       'с': no_adj,
                       'ф': no_adj,
                       'х': no_adj,
                       'ц': no_adj,
                       'ч': no_adj,
                       'ъ': no_adj,
                       'ы': no_adj,
                       'э': no_adj,
                       'ю': no_adj,
                       'я': no_adj},
                 'п': {'р': horiz_adj,
                       'т': similar_letter,
                       'с': no_adj,
                       'у': no_adj,
                       'ф': no_adj,
                       'х': no_adj,
                       'ц': no_adj,
                       'ч': no_adj,
                       'ш': no_adj,
                       'щ': no_adj,
                       'ъ': no_adj,
                       'ы': no_adj,
                       'ь': no_adj,
                       'э': no_adj,
                       'ю': no_adj,
                       'я': no_adj},
                 'р': {'т': vert_adj,
                       'с': no_adj,
                       'у': no_adj,
                       'ф': no_adj,
                       'х': no_adj,
                       'ц': no_adj,
                       'ч': no_adj,
                       'ш': no_adj,
                       'щ': no_adj,
                       'ъ': no_adj,
                       'ы': no_adj,
                       'ь': no_adj,
                       'э': no_adj,
                       'ю': no_adj,
                       'я': no_adj},
                 'с': {'ч': horiz_adj,
                       'т': no_adj,
                       'у': no_adj,
                       'ф': no_adj,
                       'х': no_adj,
                       'ц': no_adj,
                       'ш': no_adj,
                       'щ': no_adj,
                       'ъ': no_adj,
                       'ы': no_adj,
                       'ь': no_adj,
                       'э': no_adj,
                       'ю': no_adj,
                       'я': no_adj},
                 'т': {'ь': horiz_adj,
                       'у': no_adj,
                       'ф': no_adj,
                       'х': no_adj,
                       'ц': no_adj,
                       'ч': no_adj,
                       'ш': no_adj,
                       'щ': no_adj,
                       'ъ': no_adj,
                       'ы': no_adj,
                       'ь': no_adj,
                       'э': no_adj,
                       'ю': no_adj,
                       'я': no_adj},
                 'у': {'ц': horiz_adj,
                       'ы': vert_adj,
                       'ю': similar_letter,
                       'ф': no_adj,
                       'х': no_adj,
                       'ч': no_adj,
                       'ш': no_adj,
                       'щ': no_adj,
                       'ъ': no_adj,
                       'ь': no_adj,
                       'э': no_adj,
                       'я': no_adj},
                 'ф': {'ы': horiz_adj,
                       'ц': vert_adj,
                       'ч': vert_adj,
                       'щ': similar_letter,
                       'ш': similar_letter,
                       'х': no_adj,
                       'ъ': no_adj,
                       'ь': no_adj,
                       'э': no_adj,
                       'ю': no_adj,
                       'я': no_adj},
                 'х': {'ъ': horiz_adj,
                       'э': vert_adj,
                       'ц': no_adj,
                       'ч': no_adj,
                       'ш': no_adj,
                       'щ': no_adj,
                       'ы': no_adj,
                       'ь': no_adj,
                       'ю': no_adj,
                       'я': no_adj},
                 'ц': {'ы': vert_adj,
                       'ч': no_adj,
                       'ш': no_adj,
                       'щ': no_adj,
                       'ъ': no_adj,
                       'ь': no_adj,
                       'э': no_adj,
                       'ю': no_adj,
                       'я': no_adj},
                 'ч': {'я': horiz_adj,
                       'ы': vert_adj,
                       'щ': similar_letter,
                       'ш': similar_letter,
                       'ъ': no_adj,
                       'ь': no_adj,
                       'э': no_adj,
                       'ю': no_adj},
                 'ш': {'щ': horiz_adj,
                       'ъ': no_adj,
                       'ы': no_adj,
                       'ь': no_adj,
                       'э': no_adj,
                       'ю': no_adj,
                       'я': no_adj},
                 'щ': {'я': horiz_adj,
                       'ъ': no_adj,
                       'ы': no_adj,
                       'ь': no_adj,
                       'э': no_adj,
                       'ю': no_adj,
                       'я': no_adj},
                 'ъ': {'э': vert_adj,
                       'ь': similar_letter,
                       'ы': no_adj,
                       'ю': no_adj,
                       'я': no_adj},
                 'ы': {'я': vert_adj,
                       'ы': no_adj,
                       'ь': no_adj,
                       'э': no_adj,
                       'ю': no_adj},
                 'ь': {'э': no_adj,
                       'ю': no_adj,
                       'я': no_adj},
                 'э': {'ю': diag_adj,
                       'я': no_adj},
                 'ю': {'я': no_adj}}
alphabet = 'абвгдежзийклмнопрстуфхцчшщъыьэюя'


def csub(a, b):
    global alphabet
    a, b = a.lower(), b.lower()
    if a not in alphabet or b not in alphabet:
        return no_adj
    if a == b:
        return 0.0
    elif a < b:
        return KeyboardGraph[a][b]
    else:
        return KeyboardGraph[b][a]

def str_dist(str1, str2):
    l1, l2 = len(str1), len(str2)
    arr = [[0] * (l1 + 1) for x in range(l2 + 1)]
    for i in range(1, l2 + 1):
        arr[i][0] = i * cins
        for j in range(1, l1 + 1):
            arr[0][j] = j * cdel
        for i in range(1, l2 + 1):
            for j in range(1, l1 + 1):
                c = csub(str1[j - 1], str2[i - 1])
                arr[i][j] = min(arr[i][j - 1] + cdel,
                                arr[i - 1][j] + cins,
                                arr[i - 1][j - 1] + c)
                return arr[l2][l1]
def main():
    global alphabet
    print(',' + ','.join(alphabet))
    for a in alphabet:
        to_p = a
        for b in alphabet:
            to_p += ',' + str(csub(a, b))
        print(to_p)
        
if __name__ == '__main__':
    main()
    
    
                 
                       
                       
                       
                 
                       
                       
                       
                     
                 
                       
                       
                       
                 
                       
                       
                       
